### ISSUE TITLE
/import feature successor

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#507]
I was thinking oh why the current import feature feels wrong.

1) I can't change it easily. #473 as proposed is an overly fancy fix

2) I don't like /commands cos they are hard to type on mobile and they cause issues like #500 

3) Security aspect restricting /import to logged in users makes for terrible github login UX on mobile browsers/PWA

4) fact that the command disappears after we run it

5) I also dont like that we press `ask gpt` to do something that gpt has nothing to do with.

So I have have the simplest possible solution. Allow one to define POST commands via a yaml textbox in chatcraft options. Eg we would implement current solution by having a default value:
```yaml
handler_url: /proxy
method: GET
match: \/import https?:\/\/\S+
```
this would match current behavior of sending commands that look like 
* `/import https://www.example.com/file.pdf`
* `/import https://www.google.com/file.png`

So upon pressing enter:
1. chatcraft will check if the message matches any of the patterns specified
2. send request with entire message to url specified. `/import?message=/import%20https://www.google.com/file.png`

Response from that url endpoint should then be SSE streamed(can be a followup) back into next message with a clear indicator that it came from chatcraft itself. The endpoint could choose to provide an error message, such as asking for auth.

Since I want a behavior where I can paste urls in without any typing and I wanna use scrape2md, I would extend this with
```yaml
handler_url: /proxy
method: GET
match: \/import https?:\/\/\S+
---
handler_url: https://taras-scrape2md.web.val.run/
match: https?:\/\/\S+
```

We could later consider auth variables like $GITHUB_AUTH_TOKEN to this.
```yaml
handler_url: /proxy
method: POST
match: \/import https?:\/\/\S+
options:
  env:
    - name: GITHUB_AUTH_TOKEN
    - value: $GITHUB_AUTH_TOKEN
```

This seems easy to implement and could be very extensible. yaml should get validated and not let user save changes unless it matches some schema. This could also be done in a followup.

**Comment by tarasglek** [comment]
Cool thing is that we could also allow these patterns to match ai responses...eg provide a run-custom-handler button to validate chatcraft output.

```yaml
handle_url: https://some/url/with-dockerfile/validator
match: "^```docker"
match:
  multiline: true
  model_output: true
```

We could move all run-on-server stuff to this

**Comment by tarasglek** [comment]
Obviously one could build a complex ui over this, but yaml gets us going sooner

**Comment by tarasglek** [comment]
I would like to get the following example working in first rev of this feature:
```yaml
handler_url: /proxy
method: GET
match: \/import https?:\/\/\S+
---
handle_url: https://taras-scrape2md.web.val.run/
match: https?:\/\/\S+
```
