### ISSUE TITLE
Markdown responses messed up with redundant Backticks

### ISSUE THREAD

**Issue by Amnish04** [tarasglek/chatcraft.org#547]
In https://github.com/tarasglek/chatcraft.org/pull/519#issuecomment-2029721340, @tarasglek found that the markdown responses are being messed up.

![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/982372d2-6151-46b2-bea1-62df71e2a91d)

This is likely because some part of the code responsible for rendering messages in adding backticks where it shouldn't.

The testing was done with this **URL**:

https://taras.glek.net/post/markdown.download/

and Web Handler Config:
```yaml
- handlerUrl: https://taras-scrape2md.web.val.run/
  method: GET
  matchPattern: ^https:\/\/\S*$
```
